// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package kirilenko.messenger;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string author = 1;</code>
   */
  java.lang.String getAuthor();
  /**
   * <code>string author = 1;</code>
   */
  com.google.protobuf.ByteString
      getAuthorBytes();

  /**
   * <code>string date = 2;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 2;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string content = 3;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
